import type { Metadata } from "next";
import "./globals.css";
import { Inter, Quicksand, ADLaM_Display, Dancing_Script } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

const quicksand = Quicksand({
  subsets: ['latin'],
  display: 'swap',
});

const adLaM = ADLaM_Display({
  subsets: ['latin'],
  weight: '400',
});

const dancing = Dancing_Script({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}> 
      <body>
        {/* 自定义的 header 组件 */}
        {/* <Header/> */}
        {children}
      </body>
    </html>
  );
}
